<?php
// $Id: userloginbar.module,v 1.1.2.1 2009/01/17 17:58:12 ebizondrupalservices Exp $


/*
 * Userloginbar is a module written by developers at Ebizon Technologies (www.ebizontek.com). It is the implementation of http://drupal.org/node/92657#comment-792952. This module creates a new user login bar block.
 */

/**
 * Implementation of hook_menu().
 */
function userloginbar_menu() {

  $items = array();

  $items['admin/settings/userloginbar'] = array(
    'title' => 'UserloginBar Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('userloginbar_admin'),
    'access arguments' => array('administrator content'),
  );

  return $items;
}

/** implementing the new user login block */
function userloginbar_block($op = 'list', $delta = 0) {
  if ($op == 'list') {
    $blocks[0]['info'] = t("User Login Bar Block");
    return $blocks;
  }
  elseif ($op == 'view') {

    $block['content'] = theme('userloginbar');
    return $block;
  }
}

/**
 * Implementation of hook_theme()...
 */
function userloginbar_theme() {
  return array(
    'userloginbar' => array('arguments' => array()),
  );
}

/**
 * Theming function for messages.
 */
function theme_userloginbar() {
//   drupal_add_css(drupal_get_path('module', 'userloginbar') .'/sites/all/themes/pmi/css/layout.css');
  global $user;
  $output = '';

  if (arg(0) == "user" && !is_numeric(arg(1))) {

    return;

  }
  if (!$user->uid) {
	$val=str_replace('Username or e-mail: ','',drupal_get_form('user_login_block'));
	$output=str_replace('Password: ','',$val);
    //$output .= str_replace('Username or e-mail: ','',drupal_get_form('user_login_block'));
	//print_r($output);
  }
  else if (!variable_get('disable_welcome_box', FALSE)) {
    $output .= t('<p class="user-info">Hi !user, welcome back.</p>', array('!user' => theme('username', $user)));

    $output .= theme('item_list', array(
        l(t('Your account'), 'user/'. $user->uid, array('title' => t('Edit your account'))),
        l(t('Sign out'), 'logout'),
      ));
  }

  $output = '<div id="user-login-form">'. $output .'</div>';

  return $output;
}

function userloginbar_form_alter(&$form, $form_state, $form_id) {
  global $form_values;
  switch ($form_id) {
    case 'user_login_block':
      $form['#action'] = '?q=user&'. drupal_get_destination();
      $form['#method'] = 'post';
    

        $form ['name']['#attributes'] = array('class' => 'login-inpt marg_T4 marg-L6');
  	$form ['name']['#required']='';
 	$form ['pass']['#required']='';
$form ['name']['#value'] ='Username or E-mail';
$form['name']['#attributes']['onblur'] = "if (this.value == '') {this.value = '".$form['name']['#value']."';}";
$form['name']['#attributes']['onfocus'] = "if (this.value == '".$form['name']['#value']."') {this.value = '';}";
	$form['submit']['#attributes'] = array('class' => 'btn-go marg-L6 marg-R9 right');

	$form ['pass']['#attributes'] = array('class' => 'login-inpt marg_T4 marg-L6');

$form['pass']['#value'] = 'Password';
$form['pass']['#attributes']['onblur'] = "if (this.value == '') {this.value = '".$form['pass']['#value']."';}";
$form['pass']['#attributes']['onfocus'] = "if (this.value == '".$form['pass']['#value']."') {this.value = '';}";
      $form['form_id'] = array(
        '#type' => 'hidden',
        '#default_value' => 'user_login',
      );
//  echo "<pre>";
// print_r($form);

      $items = array();

//       if (variable_get('user_register', 1)) {
//         $items[] = l(t('Register'), 'user/register', array('title' => t('Create a new user account.'))) .' | &nbsp;';
//       }


$items[] = l(t('forgot password?'), 'user/password', array('attributes' => array('title' => t('Request new password via e-mail.'),'class'=> 'right')));


  
//  echo "<pre>";
// print_r($items);

      $form['links'] = array('#value' => theme('item_list', $items));


      break;
  }
}

function userloginbar_admin() {
  $form['text'] = array(
    '#type' => 'fieldset',
    '#title' => t('Userloginbar Settings'),
  );

  $form['text']['disable_welcome_box'] = array(
    '#type' => 'checkbox',
    '#title' => t('Check this box, if you want to disable welcome box when the user logs in!'),
    '#default_value' => variable_get('disable_welcome_box', FALSE),
  );

  return system_settings_form($form);
}

