<?php
function views_ignore_node_permissions_views_api()
{
  return array(
    'api' => 2,
  );
}

function views_ignore_node_permissions_views_pre_render(&$view) 
{
   //Check to see if the view has the ignore node permissions filter enabled.  If so, remove all node permissions.
   if (is_object($view->display[$view->current_display]->handler->handlers['filter']['ignore_node_permissions']))
   {
      //Thanx to Stella Power for the following code that ignores permissions.  Its not pretty, but its currently the only known working method.
      // This does the views token replacements.
      $replacements = module_invoke_all('views_query_substitutions', $view);
      $query = str_replace(array_keys($replacements), $replacements, $view->build_info['query']);
      $args = $view->build_info['query_args'];
      $offset = $view->pager['current_page'] * $view->pager['items_per_page'] + $view->pager['offset'];
      // Runs the query a second time.
      $result = db_query_range($query, $args, $offset, $view->pager['items_per_page']);
      // Overwrites the default empty result set with the results from our 2nd sql query.
      $view->result = array();
      while ($item = db_fetch_object($result)) {
         $view->result[] = $item;
      }
   }
}

/**
 * Implementation of hook_views_data().
*/
function views_ignore_node_permissions_views_data() 
{
   $data['node']['ignore_node_permissions'] = array(
    'group' => t('Node Access'),
    'title' => t('Ignore Node Permissions'),
    'help' => t('Ignore Node Permissions.  WARNING: This allows users to see the fields in this view on nodes that they do not have permission to see.  If you want to tease people with premium content, then you probably want this option enabled.  Just be mindful that whatever fields you display in this view will be visible to ALL users including anonymous users!'),
    'real field' => 'nid',
    'filter' => array(
      'handler' => 'views_ignore_node_permissions_handler_filter_ignore_node_permissions',
      //'hierarchy table' => 'term_hierarchy',
      'numeric' => TRUE,
      //'skip base' => 'node',
      'allow empty' => TRUE,
    ),
   );
   return $data;
}