<?php


/**
 * hook_form_alter
 */
function pmi_tweaks_form_alter(&$form, $form_state, $form_id) {

    /*global $user;
  if ($user->uid == 1){
    print_r($form);
  }*/

  // redirect all logins to the user page
   if ($form_id == 'user_login_block'){
      $form['#action'] = '/user';
  }

  // Set the title on the survey form
  if ($form_id == 'survey_node_form') {
    $form['buttons']['submit']['#value'] = 'Submit';

  }

    //simplenews-block-form-126
   if ($form_id == 'simplenews_block_form_126'){
      unset($form['realname1']);
      $form['submit']['#value'] = 'Get Instant Access';
      $form['#redirect'] =  '/experts-masterclass-training';
  }

}


